### ISSUE TITLE
Normal distribution for generation.time( )

### ISSUE THREAD

**Issue by NateByers** [tobadia/R0#1]
Thanks for this great package! We are using it to help estimate reproduction times in Indiana so that we can evaluate hospital capacity. 

This is a feature request, not really an issue. I wish GitHub had a feature request option.

In researching the serial interval for COVID-19 patients I found some studies that thought the cases resembled a normal distribution, with possible negative values because some secondary patients had symptoms before primary patients (eg https://wwwnc.cdc.gov/eid/article/26/6/20-0357_article). In a future version, would you be able to add normal distribution as an option in the generation.time( ) function?

Again, thanks for your work on this software.

**Comment by tobadia** [comment]
Turns out GitHub does have some sort of "feature request"n but it's a flag I have to apply to the issue... so opening one here was the right approach!

There is however a caveat with distributions that are not truncated at zero and it's very unlikely I can implement that without breaking the whole optimization routines. In all methods (except for AR that only focuses on final epidemic size vs pop. size), onset of new cases _j_ are assumed to have been generated by index cases _i_, requiring _Tj_ > _Ti_. Allowing for negative generation times would violate that assumption.
The GT is defined as the time lag between infection of an index case and its secondary case(s), so it can't be negative. What _could_ be negative though is the serial interval, _i.e._ the "time to symptom onset" (assuming the index case symptoms would start after those of the person he infected). The GT is sometimes substituted for the SI, but here it would make chains of transmission impossible.

From here, I see two different approaches: 

1. Estimate a GT from a subset of serial intervals (those positive only), but that would likely be biased; in that case you could use the `"empirical"` GT type and provide it with proportions (similarly to a PDF) estimated from the discretized observations of serial intervals.
2. Estimate a 'true' GT distributions using contact-tracing data that would have confirmed chains of transmission. This would be ideal, but requires access to such data...

I suggest you have a quick look at the paper we published along with the package [available from BMC Medical Informatics & Decision Making](https://doi.org/10.1186/1472-6947-12-147). In all equations the GT is denoted as _w_ and you'll see easily it can't be negative.

Out of curiosity, is it [that recent CDC report](https://wwwnc.cdc.gov/eid/article/26/6/20-0357_article) that prompted this question ?

**Comment by NateByers** [comment]
Yes, after submitting this I realized that it would be hard to use a distribution that allowed negative values. That would mean the secondary patient infected the primary patient?

And yes, it looks like the other places I read about a normal distribution were actually referencing that CDC report.

This is not my area of expertise. I'm just helping develop some R code and Shiny apps to help do semi-real-time assessment of the curve in our corner of the world. I appreciate your help with this. I think I'll attempt to use the empirical option.

Thanks for the response!
